name: Deploy Analysis Results to GitHub Pages

on:
  workflow_run:
    workflows: ["On-Demand Repository Analysis"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Download analysis artifacts
      if: github.event_name == 'workflow_run'
      uses: actions/download-artifact@v4
      with:
        name: analysis-*
        path: docs/results/
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'docs'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4